robertkrimen/otto

reflect_test.go
runtime.go

Javascript uses int64 (literals) and float64 (default) representations for numbers so to allow easy use of go funcs apply automatic conversion for function parameters where it is safe to do so.

Automatic numeric parameter conversion

---

reflect_test.go
runtime.go

Add support for go funcs which return multiple values by returning them as an array.
In the future this can be used along side destructuring assignment to provide a nice way to deal with multiple value returns e.g.
[val, err] = MyGoFunc()

Support go multiple return values as an array

---

dbg/dbg.go
underscore/source.go

the tiny spacing changes done with go version go1.4.2 darwin/amd64:
```find . -name '*.go' | xargs gofmt -w```

minor spacing changes for gofmt compliance

---

bug_test.go
cmpl_evaluate_statement.go

Fix toValueArray causing "missing runtime" errors due to use of toValue instead of self.toValue which causeed issues with passing values to Otto.Call(...).

Fix argument processing for call

---

reflect_test.go
runtime.go
value.go

If there is a common type for all values in an array export to a slice of that type otherwise return a slice of interfaces.

Export arrays to common type if possible

---

reflect_test.go
runtime.go
value.go

When automatically converting a float to int type ensure we don't loose any precision.

Prevent loss of float precision

---

reflect_test.go
runtime.go

Add support for the final parameter to a variadic function to be a slice.
Add support for conversion of slice parameters.
Expand numeric conversion support to include all int and uint types as source types. This allows the result of bitwise calculations (int32) to be passed in as parameters.

Improve method call parameter processing

---

bug_test.go
clone.go

When copying a runtime which contains objects with property accessors ({g,s}etters)
```
$ go test -v -run=Test_issue86
=== RUN Test_issue86
~~~ FAIL: (Terst)
--- FAIL: Test_issue86 (0.00 seconds)
panic: in.value.(Value) != true [recovered]
panic: in.value.(Value) != true [recovered]
panic: in.value.(Value) != true
goroutine 20 [running]:
runtime.panic(0x2f5400, 0x2086ed7e0)
/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
testing.func·006()
/usr/local/go/src/pkg/testing/testing.go:416 +0x176
runtime.panic(0x2f5400, 0x2086ed7e0)
/usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
_/Users/tim/repositories/github.com/sdgoij/otto/terst.func·001()
/Users/tim/repositories/github.com/sdgoij/otto/terst/terst.go:475 +0xf5
runtime.panic(0x2f5400, 0x2086ed7e0)
/usr/local/go/src/pkg/runtime/panic.c:248 …
```

Fix panic: in.value.(Value) != true

---

clone.go
clone_test.go

Previously, the following code would panic:
```
vm := otto.New()
vm.Run(`var x = Object.create(null, {
x: {
get: function() {},
set: function() {},
},
})`)
vm.Copy()
```
Now, it doesn't. Magic!

fix cloning getter/setter props

---

otto_test.go

This is a P/R with a couple of tests that show a difference that is currently biting me a bit.
We're working with records that will be of the form map[string]interface{}.
If I Set() the map to a particular name, I can then Run code that calls a function and passes that name as an argument to a precompiled function.  This is the first test and it passes.
However, if I Call() the function name and attempt to pass the map as an argument, I get:
TypeError: invalid value (map): missing runtime: map[foo:bar answer:42] (map[string]interface {})
To the extent that I can follow the code, it does look like the two are handled differently.  Should they be?  Or am I so far off in the weeds that you can barely see me?
I tried to make the tests look like what was there as much as I could, but I wasn't …

Test map[string]interface{} using Set & Call behave the same

---

otto.go
otto_test.go
stash.go

This change introduces a Context method to otto that allows developers to get
information about the current execution context. The method returns a Context
struct that contains information such as the filename, line and column of the
current execution, the current value of this, the stacktrace and the available
symbols at the current context.
Resolves #145

Add Context method to aid debugging

---

ast/comments.go
ast/comments_test.go
ast/node.go
cmpl_parse.go
parser/comments_test.go
parser/expression.go
parser/lexer.go
parser/lexer_test.go
parser/parser.go
parser/parser_test.go
parser/statement.go

This change will add a comment map to the parser, from where parsed comments are stored, indexed by nodes.
It will solve issue #148

Storing comments in a commentmap

---

type_go_slice.go
type_go_slice_test.go

Developers can define methods on slices by declaring a custom type. This allows access of slice methods inside the javascript VM.

Have goSliceGetOwnProperty check methods as well

---

array_test.go
builtin_array.go

Currently, `builtinArray_sort()` is O(n^2) operation if `sortCompare()` always returns 0.
It is common to deal with sparse arrays (almost all values are 0)
and this PR will improve performance in these cases.
```js
// sort.js
var array = new Array(1000).join('0').split('');
var count = 0;
array.sort(function (a, b) {
count++;
return a - b;
});
console.log(count);
```
```sh
$ time node sort.js
998
real    0m0.141s
user    0m0.000s
sys     0m0.000s
$ time otto sort.js
498501
real    0m3.627s
user    0m0.000s
sys     0m0.000s
$ time otto/otto sort.js # this version
998
real    0m0.059s
user    0m0.000s
sys     0m0.000s
```

Improve performance to sort array with the same values

---

error_test.go
otto.go

This change adds a handful of functions to `otto.Otto` type that make
it easier to create proper `Error` values from native code. Previously,
the only way to do this was to call the error's constructor from
JavaScript like `vm.Call("TypeError", "message")`. `Call` can fail for
various reasons, and also modifies the current call stack.
These new functions can't fail, and since they don't involve any
JavaScript execution, won't modify the call stack. The new functions
are:
* `MakeCustomError(name, message string) Value`
* `MakeRangeError(message string) Value`
* `MakeSyntaxError(message string) Value`
* `MakeTypeError(message string) Value`
`MakeCustomError` creates an `Error` object with a specific `name` value.
The other functions cover some common error types, and call specific
functions …

add error creator functions

---

builtin_error.go
error.go
error_test.go
type_error.go

Popular runtimes (V8 [1], SpiderMonkey [2], IE [3]) support a `stack`
property on Error objects to get the error's stack as a string.
This change adds support to otto for this same feature. It's implemented
in a similar way to V8, using a getter function. This avoids generating
the stack trace (which is done in a loop with string manipulation etc)
unless the user requests it. There's no standard, or even trend, for the
actual _content_ of `stack`, so we basically just copy what V8's traces
look like.
[1]: https://github.com/v8/v8/wiki/Stack%20Trace%20API
[2]: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Error/stack
[3]: http://msdn.microsoft.com/en-us/library/windows/apps/hh699850.aspx

support the non-standard Error.stack property

---

builtin.go
error.go
file/file.go
otto.go
parser/lexer_test.go
parser/parser.go
parser/parser_test.go
runtime.go
script.go
sourcemap_test.go
testing_test.go

This is pretty rough at the moment, but I plan to clean it up and figure out some tests for it.

Source maps

---

error.go
error_test.go

See #202 - newError() was crashing on new Otto instances, because `rt.scope` was nil.

Fix for #202

---

builtin_string.go
string_test.go

This is in a simple case, not with regexes. I suspect there is a similar optimization available in the neighboring code, but I wanted to get some feedback on this change first.
Before: `BenchmarkSplit-8	   20000	     77864 ns/op`
After: `BenchmarkSplit-8	  200000	      8017 ns/op`
Test run with `go test -bench=BenchmarkString_split`
edit:
changed comment to reflect move of test to strings_test.go.

made string splits *much* faster

---

runtime.go
runtime_test.go

How to recreate the issue:
-From javascript, call a Go function that returns `[]string`, and store in a javascript variable.
-Pass that value, unmodified, to another Go function that takes `[]string` as a parameter.
-The parameter will be the correct length but will be all empty strings.
I ran into this issue with other types of arrays as well.
Stepping through the code, I found that arrays constructed in the otto environment have `class` = "Array", and have `properties` filled with values, using index "0", "1", "2", and so on.  My array created in Go has `class` = "GoArray", and does not have properties.  Inside `convertCallParameter`, inside the `case reflect.Slice` portion of the main switch statement, inside the loop, the existing code refers to `o.property[...]`, which has no …

fix for casting GoArrays on in convertCallParameter

---

value_boolean.go
value_test.go

As mentioned in #232:
> From looking at value_string.go, it looks like value_boolean.go should be handling []uint16 as a UTF-16 string and returning true for length > 0, false otherwise.

Handle []uint16 to boolean conversion (resolves #232)

---

parser/lexer_test.go
testing_test.go
underscore_test.go

This fixes #207 replacing the `./terst` relative import with `github.com/robertkrimen/otto/terst`.

Replaced './terst' relative import with qualified name.

---

ast/node.go
parser/parser_test.go

Fixed the ast position of ThisExpression.

ast: ThisExpression.Idx1() should point to the end of `this`

---

type_go_map.go
type_go_map_test.go

Background:
When methods are attached on a map type like so:
```
type Foo map[string]string
func (f Foo) Bar() {
fmt.Printf("Hello World");
}
vm := otto.New();
vm.Set("foo", Foo{});
vm.Run(`
foo.Bar();
`);
```
You get:
```
Error in Run: TypeError: 'Bar' is not a function
```
The Fix:
I looked into how/why the same works for arrays. After
all array properties are tested (such as length, and any integer-based members),
the code then looks for any methods attached to that type.
This change literally copies that code over into
maps.
This is very useful when working with the http.Request object which
has the http.Header type that is a map[string][]string, with a lot
of useful methods attached to it.

Other methods callable on Maps

---

ast/walk.go
ast/walk_example_test.go

Add an `ast.Walk` utility function to traverse the AST in depth-first order.

Add a an ast.Walk utility function

---

functional_benchmark_test.go

This change adds two types of tests:
1. First some regular Test* tests that functionally
ensure the test cases are correct.
2. A few Benchmark* tests that then allow us to
measure Otto's performance under various functional scenarios.
The basic tests are just sorting, but I'm planning over time
to bring in more advanced tests (like the CryptoAES) from
popular benchmarking suites (JetStream for instance.)
I intend to run profiler on these tests to find any
ottlenecks or low-hanging fruit that can help speed up
Otto for real-world use-cases.
Next up after this is to add some heavy underscorejs
benchmarks.

Added functional benchmarks

---

array_test.go
builtin_array.go

According to https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice, Array.splice with a single argument should remove all items starting with said argument. Otto incorrectly treats this the same as if 0 were specified, in which case it (correctly) removes nothing.

Fix Array.splice(n) with single argument

---

file/file.go
parser/parser.go

Avoids possible golang error discussed in #291.
- Seems like no real changes in the code are needed.
- Seems like no tests are broken.
- Tested some scripts to run and it was successful.

updating sourcemaps from go-sourcemaps to latest release

---

regexp_test.go
type_regexp.go

If `lastIndex` is set on `RegExp` the offset will be incorrectly increased by `lastIndex` even if there is no match. `FindStringSubmatchIndex` returns `-1` if there is no match and we should keep `-1` as is.

Fix RegExp.exec incorrect groups offsets if lastIndex is set

---

go.mod
go.sum

this pr adds a go.mod file to this package. go depends to github user name in path, so I used a base repo name in path and it will not build if clone directly from my fork, go.mod should be downloaded manually and added to existing installation.
to test that it works, you can do this:
1. create a fresh go environment:
mv ~/go ~/go1
2. go get source repo:
go get github.com/robertkrimen/otto
it will download it, but will not build by default, because some dependencies will be missing.
3. manually add go.mod from my fork.
4. try go build.
it should automaticly load up all dependencies and build without errors.

add go.mod file

---

testing_test.go

For slow computing machines, 2 seconds is too short to PASS the testing. #337
Signed-off-by: Jongmin Kim <jmkim@pukyong.ac.kr>

Extend testing timeout to 20 secs (fix #337)

---

reflect_test.go
value.go
value_test.go

Reverts robertkrimen/otto#325
This caused a regression in TestGoStructNilBoolPointerField

Revert "feat: support null value returns for toValue"

---

underscore/underscore.go

Found using https://go-critic.github.io/overview.html#unlambda-ref

underscore: use func value instead of wrapping lambda

---

value.go
value_test.go

- I believe this is a more appropriate solution than #377 as it takes
into account the types of elements in sub arrays, slices, etc.
- This should also fix #279 which was apparently closed although the
issue still existed.

Fix a panic in value export when an array has multiple types of arrays

---

otto.go
value.go
value_test.go

Value and Object now conform to the json.Marshaler interface and produce the
correct JSON when passed (directly or indirectly) to json.Marshal().
Before, both types would marshal as "{}" because they're structs with no public
fields.
This fixes some nasty problems marshaling object trees that mix Go and JS
collections. This can happen when you pass a Go collection into a JS function,
which modifies it adding JS values; and then back in Go you marshal the
collection to JSON. Before this commit the JS values would marshal to "{}".
(The new unit test TestNestedJSONMarshaling demonstrates this.)
Fixes #262

Implemented MarshalJSON for Value and Object

---

go.mod
go.sum

Turns of that v1.1.10 does not have an explicit LICENSE file and that was added in v1.2.0, and it would be very nice to be able to use this package without alarming compliance checks.
Signed-off-by: eriknordmark <erik@zededa.com>

Update github.com/chzyer/logex to newer version

---

issue390_test.go
runtime.go

Don't look on interface types for field names, as it causes a panic.
Fixes #390

fix: field index on interface

---

.github/workflows/test-lint.yml

Remove skip-cache: true and restore skip-pkg-cache: true and skip-build-cache: true so that we still cache golangci-lint results
which skip-cache: true disables.

ci: enable golangci-lint cache

---

builtin_string.go
regexp_test.go
string_test.go
type_regexp.go
type_string.go

Fix string lengths for strings containing code points which require a Surrogate pair encoding in utf16.
Fixes #388

fix: string lengths

---

bug_test.go
runtime.go

Fix #369 
This fixes the issue with no apparent regressions, but since I don't know why this check was in place, I'm not sure that's the right solution.

fieldIndexByName: extract type from interface in fieldIndexByName

---

bug_test.go
runtime.go

Allow pointers to structs in fieldIndexByName.
Also:
* Use reflect.Type.Elem() vs reflect.ValueOf(t).Elem().Type().

fix: field pointers in fieldIndexByName

---

issue_test.go
runtime.go
type_go_array.go
type_go_map.go
type_go_slice.go
type_go_struct.go

Fix array writes not being persisted by passing in writeable reflect.Value when available instead of .Interface() which looses that property.
Also:
* Use value.IsValid() instead of comparison with zero entry.
* Use propertyLength instead of literal.
Fixes #386

fix: array writes

---

issue_test.go
runtime.go

Ensure that a panic is caught if thrown in a try catch block.
Fixes #382

fix: catch panic in try catch

---

functional_benchmark_test.go

Reduce the item count in JavaScript sort benchmarks to something more reasonable given the memory pressure they cause.
Fixes #378

fix: javascript sort time

---

consts.go
issue_test.go
runtime.go
type_array.go
type_go_slice.go

Add support for direct use of push to go slices without converting to array using .slice().
Fixes #357
Also:
* Add classGoSlice and use it, to make it clear the type when debugging.

feat: support push to go slices

---

error.go

Print the error with stack when using %#v.
Fixes #363

feat: error with stack on %#v

---

date_test.go

Fix constant overflow for date tests on 32bit architectures which have int as 32bit not 64bit.
Fixes #351

fix: constant overflow for date tests

---

parser/parser_test.go
parser/statement.go

In nested do-while statements, a semicolon after the inner `while` threw a parsing error. This change checks for the optional semicolon.
Fixes #309

fix: allow semicolon in nested do-while statements.

---

builtin_date.go
date_test.go
issue_test.go
type_date.go

Use time.UnixMilli instead of UnixNano for time calculations to avoid underflow / overflow issues.
BREAKING CHANGE: Use a GMT fixed time zone for UTC to mimic toUTCString behaviour of Javascript which outputs in GMT not UTC.
Fixes #302

fix!: date underflow / overflow and utc

---

global.go
issue_test.go
runtime.go
type_error.go

Fix stack being truncated due to double conversion to _error.
Fixes #329

fix: stack panic truncation

---

issue_test.go
value.go

When exporting a map check for values which are otto.Value and process them. This is a one level export and no additional traversal is done.
Fixes #252

fix: map export

---

builtin_array.go
issue_test.go

While not specified in the ECMA specification the current index has been typed as number by others, so match this instead of passing as string.
Fixes #177

fix: reduce current index type

---

reflect_test.go
type_go_array.go
type_go_map.go
type_go_slice.go
value.go
value_test.go

When putting JavaScript objects into _go*object use exported values. This reverts PR #467 in favour of this more complete work.
Fixes #118 #252
Co-authored-by: Dmitry Panov <dop@itoolabs.com>

feat: use exported methods when setting go values

---

README.markdown

This fixes the example code for cleaning up long-running VMs.  Previously, they were killed after the timeout: the goroutine tracking this timeout holds a reference to the VM, therefore keeping the entire VM in memory for the duration of the configured timeout regardless of whether it has already completed its execution.
This change adds a second layer of communication to the watchdog goroutine, so that it will terminate itself if the VM has exited within the timeout.  This allows the VM to be garbage collected if no other references to the VM exist.

fix example to clean up watchdog goroutine

---

array_test.go
builtin_number.go
go.mod
go.sum
issue_test.go
locale.go
number_test.go

Add support for Number.toLocaleString() which was previously just using toString.
Default locale is: en-US
Fixes #285

fix: number locale support

---

ast/node.go
ast/walk_test.go

Fix invalid Idx1() return for NewExpression when there are no parenthesis.

fix(ast): invalid idx1 for new expression

---

value_number.go

Fix toInt32, toUint32 conversions which caused test failures on arm64.
Fixes #457

fix: number to int conversions

---

builtin_regexp.go
issue_test.go

Fix RegExp panic when a capture doesn't match but the full expression does.

fix: missing regexp capture panic

---

.golangci.yml
tools/gen-jscore/main.go
value_number.go

Fix golangci-lint errors triggered by new version.
Disable deprecated linters.

ci: fix golangci-lint errors

---

ast/walk.go
ast/walk_test.go

This PR is to address what I think might have been an oversight in the ast package walk.go file.
When the switch runs across a BadStatement node, this causes it to default (and panic).
I have added an empty case for this node type similar to BadExpression to get around this as well as a unit test.

Add BadStatement case to walk.go to avoid panic

---

.github/workflows/test-lint.yml
.golangci.yml
builtin_date.go
object_class.go
parser/lexer.go
type_function.go

Fix lint failures introduced by new 1.53 linters
* Remove naked returns
* Accept times using local time where intended
* Allow unused parameter for now on call method
* Disable depguard which just seems to be noise
Also:
* Correct typo so we use the specified golangci-lint version in CI.
* Remove alias for time package in builtin_date.go

ci: fix lint failures

---

ast/node.go
parser/parser_test.go

Idx1 should point to the first character immediately after the node, rather than the last character of the node.

Fix Idx1 of ObjectLiteral and ArrayLiteral

---

ast/node.go
parser/expression.go
parser/parser_test.go

* Fix typo in `parseConditionlExpression`
* Fix Idx1 of ConditionalExpression to point to Alternate.Idx1()
* Fix Idx1 of SequenceExpression to point to Idx1 of the last Sequence element
* Fix Idx0 of UnaryExpression to point to the beginning of Operand in case of postfix operator
* Fix Idx1 of VariableExpression to point to the character immediately after Name if it does not have Initializer

fix: positions of expressions

---

builtin_string.go
inline.go
inline_test.go
string_test.go
tools/gen-jscore/.gen-jscore.yaml

- Adds `startsWith` to the String builtins
- Adds a test to ensure it works as intended

Feat: Add `startsWith` to String builtins

---

builtin_object.go
inline.go
object_test.go
tools/gen-jscore/.gen-jscore.yaml

This adds support for `Object.values()`, alongside tests

Support Object.values()

---

parser/expression.go
parser/parser_test.go

Example:
```js
function mergeObjects(x, y) { /* dummy body */}
mergeObjects(
{ "duck": "quack" },
{ "dog": "bark" }, // Allow trailing comma after the last argument.
);
```

Support trailing comma after the last argument.

---

parser/lexer.go
parser/lexer_test.go

`unicode.IsLetter` and `unicode.IsDigit` will not return the complete set of `ID_Start` and `ID_Continue` characters defined here:  https://www.unicode.org/reports/tr31/.

parser/lexer: correct ID_Start & ID_Continue checks

---

parser/expression.go
parser/parser_test.go

In the specific corner case where a regex contains a flag but is not followed by any symbols, the `ast.RegExpLiteral.Literal` value would drop (part of) that flag.
This happens because the `p.next()` call during the parsing of the flag wouldn't actually advance the `p.chrOffset`, and thus `endOffset` would be erroneously adjusted.
The fix is just to use the current `p.chrOffset` and then call `p.next()` afterwards.

fix: missing flag from regex literal in corner case

---

.github/workflows/release-build.yml
.github/workflows/test-lint.yml
.golangci.yml
builtin_array.go
builtin_date.go
builtin_function.go
builtin_json.go
builtin_string.go
console.go
error.go
functional_benchmark_test.go
go.mod
parser/lexer.go
parser/marshal_test.go
runtime.go
tools/tester/main.go
type_go_struct.go
type_regexp.go
type_string.go
value.go
value_test.go

Update to the oldest supported release of go v1.22 at this time.
Update golangci-lint to 1.61.0 and address all issues.
Update actions to the latest versions.

chore: update go and tools

---

builtin_string.go
string_test.go

Fix string slice and replace so they work correctly with utf8 characters.
Fixes #534

fix: string slice and replace

---

.github/workflows/release-build.yml

Update goreleaser args to use the new non-deprecated --clean.

ci: update goreleaser args
